name: result_type
version: 0.2.1
description: Result Type for Dart.
repository: https://github.com/minikin/result_type

environment:
  sdk: '>=3.0.0-179.0.dev'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  http: ^0.13.5
  test: ^1.21.4
