name: result_type
version: 1.0.0
description: Result Type for Dart.
repository: https://github.com/minikin/result_type

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.14.0

dev_dependencies:
  http: ^1.2.1
  test: ^1.24.3
