name: result_type
version: 0.0.1
description: Result Type
authors:
  - "Sasha Prokhorenko"
repository: https://github.com/minikin/dart_result_type

environment:
  sdk: ">=2.10.4 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.1