name: result_type
version: 0.2.0
description: Result Type for Dart.
repository: https://github.com/minikin/result_type

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  http: ^0.13.5
  test: ^1.21.4
