name: result_type
version: 0.3.0
description: Result Type for Dart.
repository: https://github.com/minikin/result_type

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  http: ^1.0.0
  test: ^1.24.3
